### ISSUE TITLE
Debian 8 package doesn't start

### ISSUE THREAD

**Issue by tsharpe** [hubblestack/hubble#143]
Packages install just fine but package won't start.
```
# systemctl enable hubble
Synchronizing state for hubble.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d hubble defaults
Executing /usr/sbin/update-rc.d hubble enable
Created symlink from /etc/systemd/system/multi-user.target.wants/hubble.service to /usr/lib/systemd/system/hubble.service.
```
```
# systemctl start hubble
Job for hubble.service failed. See 'systemctl status hubble.service' and 'journalctl -xn' for details.
root@debian8-512mb-hubbletest3:/etc/hubble/hubble.d# hubble -dvvv
Traceback (most recent call last):
  File "hubble.py", line 3, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "hubblestack/daemon.py", line 17, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "salt/fileclient.py", line 21, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "salt/client/__init__.py", line 30, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "salt/config/__init__.py", line 100, in <module>
  File "salt/config/__init__.py", line 90, in _gather_buffer_space
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "salt/grains/core.py", line 47, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "salt/utils/dns.py", line 28, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "salt/modules/cmdmod.py", line 34, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "salt/utils/templates.py", line 31, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "salt/utils/http.py", line 71, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "requests/__init__.py", line 84, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "urllib3/contrib/pyopenssl.py", line 46, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "OpenSSL/__init__.py", line 8, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "OpenSSL/rand.py", line 10, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "OpenSSL/_util.py", line 6, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
  File "/tmp/pip-build-oVJWxj/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 546, in load_module
AttributeError: 'module' object has no attribute '_init_cffi_1_0_external_module'
Failed to execute script hubble
```

**Comment by fossam** [comment]
For an update, currently the package has the following issue:

```
> [ERROR   ] Failed to import pygit2
> Traceback (most recent call last):
>   File "salt/utils/gitfs.py", line 88, in <module>
>     import pygit2
>   File "/tmp/pip-build-h4MS8D/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
>   File "pygit2/__init__.py", line 35, in <module>
>   File "/tmp/pip-build-h4MS8D/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
>   File "pygit2/blame.py", line 32, in <module>
>   File "/tmp/pip-build-h4MS8D/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
>   File "pygit2/errors.py", line 29, in <module>
>   File "/tmp/pip-build-h4MS8D/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
>   File "pygit2/ffi.py", line 35, in <module>
>   File "/tmp/pip-build-h4MS8D/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
>   File "pygit2/_run.py", line 54, in <module>
>   File "codecs.py", line 878, in open
> IOError: [Errno 2] No such file or directory: '/opt/hubble/hubble-libs/decl.h'
> [DEBUG   ] gitpython gitfs_provider enabled
```

**Comment by basepi** [comment]
The packages uploaded to the 2.2.1 release on Github have resolved these issues.
