### ISSUE TITLE
Unable to fetch profiles from azurefs on windows in hubble 2.2.8

### ISSUE THREAD

**Issue by yassingh** [hubblestack/hubble#223]
Hubble 2.2.8 is not able to fetch profiles from azurefs. I encountered this issue on windows server 2016. Here are some logs:
```
C:\Program Files (x86)\Hubble\PortableGit>hubble -c "C:\Program Files (x86)\Hubble\etc\hubble\hubble.conf" --version
2.2.8

C:\Program Files (x86)\Hubble\PortableGit>hubble -c "C:\Program Files (x86)\Hubble\etc\hubble\hubble.conf" hubble.audit
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "hubble.py", line 5, in <module>
  File "hubblestack\daemon.py", line 57, in run
  File "hubblestack\daemon.py", line 80, in main
  File "hubblestack\daemon.py", line 244, in run_function
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 108, in audit
    show_compliance=show_compliance)
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 406, in top
    load()
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 558, in load
    sync()
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 534, in sync
    cached = __salt__['cp.cache_dir'](path, saltenv=saltenv)
  File "C:\PROGRA~2\Hubble\salt\modules\cp.py", line 492, in cache_dir
    path, saltenv, include_empty, include_pat, exclude_pat
  File "site-packages\salt\fileclient.py", line 225, in cache_dir
  File "site-packages\salt\fileclient.py", line 1233, in file_list
  File "site-packages\salt\fileserver\__init__.py", line 891, in send
  File "site-packages\salt\fileserver\__init__.py", line 751, in file_list
  File "C:\PROGRA~2\Hubble\salt\fileserver\azurefs.py", line 305, in file_list
    storage_conn = azure.get_storage_conn(opts=envs[load['saltenv']])
TypeError: list indices must be integers, not str
Traceback (most recent call last):
  File "hubble.py", line 5, in <module>
  File "hubblestack\daemon.py", line 57, in run
  File "hubblestack\daemon.py", line 80, in main
  File "hubblestack\daemon.py", line 244, in run_function
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 108, in audit
    show_compliance=show_compliance)
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 406, in top
    load()
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 558, in load
    sync()
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 534, in sync
    cached = __salt__['cp.cache_dir'](path, saltenv=saltenv)
  File "C:\PROGRA~2\Hubble\salt\modules\cp.py", line 492, in cache_dir
    path, saltenv, include_empty, include_pat, exclude_pat
  File "site-packages\salt\fileclient.py", line 225, in cache_dir
  File "site-packages\salt\fileclient.py", line 1233, in file_list
  File "site-packages\salt\fileserver\__init__.py", line 891, in send
  File "site-packages\salt\fileserver\__init__.py", line 751, in file_list
  File "C:\PROGRA~2\Hubble\salt\fileserver\azurefs.py", line 305, in file_list
    storage_conn = azure.get_storage_conn(opts=envs[load['saltenv']])
TypeError: list indices must be integers, not str
Failed to execute script hubble
```
Here are some more observations : 
1) Hubble 2.2.8 is working fine on amazon linux  ( bug only on windows)
2) Hubble 2.2.1 does not have this issue.
3) In hubble 2.2.1 installation, I tried replacing my local 'hubblestack/extmods/fileserver/azurefs.py' with the one at github master branch, but 2.2.1 was still able to fetch profiles from azurefs.

**Comment by basepi** [comment]
@yassingh Can you try this new build? https://s3-us-west-2.amazonaws.com/hubblestack-releases/Hubble-v2.2.8.1-Setup.exe

@madchills can't reproduce the issue on this new build.

**Comment by yassingh** [comment]
I have testing the new build ( 2.2.8.1 ). It's working fine on windows. Files from azurefs are being fetched properly. 
Thanks 👍
