### ISSUE TITLE
Not able to use local json file for CVE scan

### ISSUE THREAD

**Issue by AfterSpencer** [hubblestack/hubble#423]
```
[root@hostname ~]# hubble hubble.audit cve.scan-v2
{'Failure': [], 'Success': []}
[root@hostname ~]# hubble hubble.audit cve.scan-v3
{'Compliance': '2%',
 'Failure': [{u'nss-3.28.4-11.el7_4': u'CESA-2017:2832'},
             {u'linux-firmware-20170606-56.gitc990aae.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'iwl6050-firmware-41.28.5.1-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'rubygem-rdoc-4.0.0-30.el7': u'CESA-2018:0378'},
             {u'iwl100-firmware-39.31.5.1-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'perl-Git-1.8.3.1-12.el7_4': u'CESA-2018:1957, CESA-2017:2484'},
             {u'libxml2-2.9.1-6.el7_2.3': u'CESA-2016:1292, CESA-2015:2550'},
             {u'iwl6000-firmware-9.221.4.1-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'iwl7260-firmware-22.0.7.0-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'gnupg2-2.0.22-4.el7': u'CESA-2018:2181'},
             {u'git-1.8.3.1-12.el7_4': u'CESA-2018:1957'},
             {u'iwl135-firmware-18.168.6.1-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'iwl5150-firmware-8.24.2.2-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'systemd-219-42.el7_4.1': u'CESA-2018:0260'},
             {u'libyaml-0.1.4-11.el7_0': u'CESA-2015:0100'},
             {u'rubygems-2.0.14.1-30.el7': u'CESA-2018:0378'},
             {u'iwl105-firmware-18.168.6.1-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'libuser-0.60-7.el7_1': u'CESA-2015:1483'},
             {u'ruby-irb-2.0.0.648-30.el7': u'CESA-2018:0378'},
             {u'libssh2-1.4.3-10.el7_2.1': u'CESA-2016:0428'},
             {u'iwl6000g2a-firmware-17.168.5.3-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'iwl2030-firmware-18.168.6.1-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'iwl3945-firmware-15.32.2.9-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'curl-7.29.0-42.el7': u'CESA-2017:3263'},
             {u'iwl2000-firmware-18.168.6.1-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'ntp-4.2.6p5-25.el7.centos.2': u'CESA-2017:0252'},
             {u'procps-ng-3.3.10-16.el7': u'CESA-2018:1700'},
             {u'samba-common-4.6.2-12.el7_4': u'CESA-2017:3260'},
             {u'dnsmasq-2.76-2.el7': u'CESA-2017:2836'},
             {u'iwl5000-firmware-8.83.5.1_1-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'ruby-2.0.0.648-33.el7_4': u'CESA-2018:0378'},
             {u'iwl4965-firmware-228.61.2.24-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'iwl6000g2b-firmware-17.168.5.2-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'wget-1.14-15.el7': u'CESA-2017:3075'},
             {u'iwl3160-firmware-22.0.7.0-56.el7': u'CESA-2018:0014, CESA-2018:0094'},
             {u'libarchive-3.1.2-10.el7_2': u'CESA-2016:1844'},
             {u'python-2.7.5-58.el7': u'CESA-2018:2123'}],
 'Success': [{'Secure packages': '579 out of 616'}]}
[root@hostname ~]#
[root@hostname ~]#
[root@hostname ~]#
[root@hostname ~]#
[root@hostname ~]# cd /
[root@hostname /]# find / -name cve_store.py
[root@hostname /]# hubble hubble.audit cve.scan-v2-salt
[ERROR   ] Exception occurred in nova module:
[ERROR   ] Traceback (most recent call last):
  File "/opt/hubble/hubble-libs/hubblestack/extmods/modules/hubble.py", line 295, in _run_audit
    ret = func(data_list, tags, labels, **kwargs)
  File "/var/cache/hubble/files/base/hubblestack_nova/cve_scan_v2.py", line 223, in audit
    raise IOError('The file was not able to be retrieved from the salt file server.')
IOError: The file was not able to be retrieved from the salt file server.

{'Errors': [{u'/cve_scan_v2.py': {'data': 'IOError: The file was not able to be retrieved from the salt file server.',
                                  'error': 'exception occurred'}}],
 'Failure': [],
 'Success': []}

```

I think I am missing something and I can't figure it out after looking at the documentation.

Here are the files I have in /srv/salt/hubblestack_data/hubblestack_nova_profiles

centos_7.json  cve_scan_v2  cve.scan-v2.yaml  top.nova

```
cat top.nova
nova:
  '*':
    - cve.scan-v2
  #  - network.ssh
  #  - network.smtp
  #'web*':
  #  - cis.centos-7-level-1-scored-v1
  #  - cis.centos-7-level-2-scored-v1
```
```
cat cve.scan-v2.yaml
cve_scan_v2:
    ttl: 86400
    url: "salt://hubblestack_data/centos_7.json"
```

**Comment by basepi** [comment]
Your url appears to be wrong in your `cve.scan-v2.yaml`

You're using `salt://hubblestack_data/centos_7.json`

The file is located at `salt://hubblestack_data/hubblestack_nova_profiles/centos_7.json` (based on the path you mentioned above.)

**Comment by basepi** [comment]
Also, top.nova uses `.` as a directory separator, so you should have your yaml at `cve/scan-v2.yaml` for the top data you showed above.

**Comment by AfterSpencer** [comment]
Okay - here are the files as of now:

```
[root@hostname hubblestack_nova_profiles]# pwd
/srv/salt/hubblestack_data/hubblestack_nova_profiles
[root@hostname hubblestack_nova_profiles]# cat cve.scan-v2.yaml
cve_scan_v2:
    ttl: 86400
    url: "salt://hubblestack_data/hubblestack_nova_profiles/centos_7.json"
[root@hostname hubblestack_nova_profiles]# cat top.nova
nova:
  '*':
    - cve/scan-v2.yaml
  #  - network.ssh
  #  - network.smtp
  #'web*':
  #  - cis.centos-7-level-1-scored-v1
  #  - cis.centos-7-level-2-scored-v1

```
Run of the audit:

```
hubble hubble.audit cve.scan-v2-salt
[ERROR   ] Exception occurred in nova module:
[ERROR   ] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hubblestack-2.3.4-py2.7.egg/hubblestack/extmods/modules/hubble.py", line 295, in _run_audit
    ret = func(data_list, tags, labels, **kwargs)
  File "/usr/lib/python2.7/site-packages/hubblestack-2.3.4-py2.7.egg/hubblestack/files/hubblestack_nova/cve_scan_v2.py", line 223, in audit
    raise IOError('The file was not able to be retrieved from the salt file server.')
IOError: The file was not able to be retrieved from the salt file server.

{'Errors': [{'/cve_scan_v2.py': {'data': 'IOError: The file was not able to be retrieved from the salt file server.',
                                 'error': 'exception occurred'}}],
 'Failure': [],
 'Success': []}
[root@m0159393 hubblestack_nova_profiles]# pwd
/srv/salt/hubblestack_data/hubblestack_nova_profiles
[root@m0159393 hubblestack_nova_profiles]# cat cve.scan-v2.yaml
cve_scan_v2:
    ttl: 86400
    url: "salt://hubblestack_data/hubblestack_nova_profiles/centos_7.json"
```

**Comment by basepi** [comment]
So you still have some mismatches.

You're use `hubble.audit cve.scan-v2-salt`

Which is going to look for your file at `salt://hubblestack_nova_profiles/cve/scan-v2.yaml`

To use your file structure as you've shown, you need to change your commands a bit.

`/srv/salt/hubblestack_data/hubblestack_nova_profiles/cve/scan-v2.yaml` (note the change in location. You can't have dots in your filename, because hubble treats them as directory separators):

```
cve_scan_v2:
    ttl: 86400
    url: "salt://hubblestack_data/hubblestack_nova_profiles/centos_7.json"
```

Your top.nova doesn't matter because you're not calling hubble.top.

So, assuming you have the json at `/srv/salt/hubblestack_data/hubblestack_nova_profiles/centos_7.json`, then you can run the following:

```
hubble hubble.audit cve.scan-v2
```

Note the removal of `-salt` because that wasn't in your filename.

**Comment by AfterSpencer** [comment]
Thanks. I worked with a guy who has done stuff with salt before and we got it sorted. You got us pointed in the right direction, thanks for being responsive.

For those who don't know salt like me, here is what I ended up doing.

top.nova is in /srv/salt/hubblestack_data/hubblestack_nova_profiles
and looks like this:

```
nova:
  '*':
    - cve_scan_v2
```

There are a few files in  /srv/salt/hubblestack_data, but it seems like they can be under hubblestack_nova_profiles and work okay too.

```
ls
centos_7.json  cve_scan_v2.yaml  hubblestack_nova_profiles
```

```
cat cve_scan_v2.yaml
cve_scan_v2:
    ttl: 86400
    url: "salt://centos_7.json"
```

From there I can run the audit and it returns as expected:

```
hubble hubble.audit
{'Compliance': '0%',
 'Failure': [{u'postgresql-libs-9.2.23-3.el7_4': u'postgresql security update'},
             {u'iwl2030-firmware-18.168.6.1-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'bind-libs-9.9.4-51.el7_4.2': u'bind security update'},
             {u'bind-utils-9.9.4-51.el7_4.2': u'bind security update'},
             {u'python-libs-2.7.5-69.el7_5': u'python, tkinter security update'},
             {u'iwl3160-firmware-22.0.7.0-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'kernel-tools-libs-3.10.0-693.el7': u'kernel, perf, python security update'},
             {u'bind-license-9.9.4-51.el7_4.2': u'bind security update'},
             {u'systemd-219-42.el7_4.7': u'libgudev1, systemd security update'},
             {u'python-2.7.5-69.el7_5': u'python, tkinter security update'},
             {u'iwl6050-firmware-41.28.5.1-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'dhclient-4.2.5-68.el7.centos.1': u'dhclient, dhcp security update'},
             {u'nss-sysinit-3.28.4-12.el7_4': u'nss security update'},
             {u'libgcc-4.8.5-28.el7': u'cpp, gcc, libasan, libatomic, libgcc, libgfortran, libgnat, libgo, libgomp, libitm, libmudflap, libobjc, libquadmath, libstdc++, libtsan security update'},
             {u'nss-3.28.4-12.el7_4': u'nss security update'},
             {u'iwl5000-firmware-8.83.5.1_1-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'augeas-libs-1.4.0-2.el7_4.1': u'augeas security update'},
             {u'iwl100-firmware-39.31.5.1-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'libgudev1-219-42.el7_4.7': u'libgudev1, systemd security update'},
             {u'iwl6000g2b-firmware-17.168.5.2-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'iwl7260-firmware-22.0.7.0-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'rubygem-io-console-0.4.2-33.el7_4': u'ruby, rubygem, rubygems security update'},
             {u'iwl6000-firmware-9.221.4.1-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'rubygem-rdoc-4.0.0-33.el7_4': u'ruby, rubygem, rubygems security update'},
             {u'bind-libs-lite-9.9.4-51.el7_4.2': u'bind security update'},
             {u'iwl1000-firmware-39.31.5.1-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'ruby-irb-2.0.0.648-33.el7_4': u'ruby, rubygem, rubygems security update'},
             {u'nss-tools-3.28.4-12.el7_4': u'nss security update'},
             {u'dhcp-libs-4.2.5-68.el7.centos.1': u'dhclient, dhcp security update'},
             {u'iwl2000-firmware-18.168.6.1-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'systemd-libs-219-42.el7_4.7': u'libgudev1, systemd security update'},
             {u'rubygem-psych-2.0.0-33.el7_4': u'ruby, rubygem, rubygems security update'},
             {u'kernel-tools-3.10.0-693.el7': u'kernel, perf, python security update'},
             {u'gnupg2-2.0.22-5.el7_5': u'gnupg2 security update'},
             {u'procps-ng-3.3.10-17.el7_5.2': u'procps security update'},
             {u'kernel-3.10.0-693.el7': u'kernel, perf, python security update'},
             {u'libcurl-7.29.0-42.el7_4.1': u'curl, libcurl security update'},
             {u'perl-Git-1.8.3.1-14.el7_5': u'emacs, git, gitk, gitweb, perl security update'},
             {u'iwl3945-firmware-15.32.2.9-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'iwl135-firmware-18.168.6.1-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'iwl6000g2a-firmware-17.168.5.3-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'rubygems-2.0.14.1-33.el7_4': u'ruby, rubygem, rubygems security update'},
             {u'iwl4965-firmware-228.61.2.24-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'rubygem-bigdecimal-1.2.0-33.el7_4': u'ruby, rubygem, rubygems security update'},
             {u'iwl105-firmware-18.168.6.1-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'dnsmasq-2.76-2.el7_4.2': u'dnsmasq security update'},
             {u'linux-firmware-20170606-58.gitc990aae.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'systemd-sysv-219-42.el7_4.7': u'libgudev1, systemd security update'},
             {u'wget-1.14-15.el7_4.1': u'wget security update'},
             {u'dhcp-common-4.2.5-68.el7.centos.1': u'dhclient, dhcp security update'},
             {u'libgomp-4.8.5-28.el7': u'cpp, gcc, libasan, libatomic, libgcc, libgfortran, libgnat, libgo, libgomp, libitm, libmudflap, libobjc, libquadmath, libstdc++, libtsan security update'},
             {u'wpa_supplicant-2.6-5.el7_4.1': u'wpa_supplicant security update'},
             {u'libstdc++-4.8.5-28.el7': u'cpp, gcc, libasan, libatomic, libgcc, libgfortran, libgnat, libgo, libgomp, libitm, libmudflap, libobjc, libquadmath, libstdc++, libtsan security update'},
             {u'iwl5150-firmware-8.24.2.2-58.el7_4': u'iwl100, iwl1000, iwl105, iwl135, iwl2000, iwl2030, iwl3160, iwl3945, iwl4965, iwl5000, iwl5150, iwl6000, iwl6000g2a, iwl6000g2b, iwl6050, iwl7260, iwl7265, linux security update'},
             {u'git-1.8.3.1-14.el7_5': u'emacs, git, gitk, gitweb, perl security update'},
             {u'python-perf-3.10.0-693.el7': u'kernel, perf, python security update'},
             {u'curl-7.29.0-42.el7_4.1': u'curl, libcurl security update'},
             {u'rubygem-json-1.7.7-33.el7_4': u'ruby, rubygem, rubygems security update'}]}
```

**Comment by basepi** [comment]
Glad you figured it out.
