### ISSUE TITLE
Hubblestack installation fails on SLES 12

### ISSUE THREAD

**Issue by claudekenni** [hubblestack/hubble#443]
I'm trying to install Hubblestack on a SLES12 Machine. After fixing errors with the required packages and installing them manually first I get the following error

```
root@fitl08v008:/root/hubble > /usr/bin/python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to hubblestack.egg-info/requires.txt
writing hubblestack.egg-info/PKG-INFO
writing top-level names to hubblestack.egg-info/top_level.txt
writing dependency_links to hubblestack.egg-info/dependency_links.txt
writing entry points to hubblestack.egg-info/entry_points.txt
reading manifest file 'hubblestack.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'hubblestack.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/hubblestack
copying build/lib/hubblestack/hangtime.py -> build/bdist.linux-x86_64/egg/hubblestack
creating build/bdist.linux-x86_64/egg/hubblestack/files
creating build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/win_gp.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/openssl.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/firewall.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/win_pkg.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/win_reg.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/sysctl.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/netstat.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/cve_scan_v2.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/win_auditpol.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/vulners_scanner.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/misc.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/systemctl.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/cve_scan.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/mount.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/service.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/pkg.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/grep.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/command.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/stat_nova.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/win_firewall.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/__init__.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/win_secedit.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/hubblestack_nova/pkgng_audit.py -> build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova
copying build/lib/hubblestack/files/__init__.py -> build/bdist.linux-x86_64/egg/hubblestack/files
copying build/lib/hubblestack/daemon.py -> build/bdist.linux-x86_64/egg/hubblestack
creating build/bdist.linux-x86_64/egg/hubblestack/extmods
creating build/bdist.linux-x86_64/egg/hubblestack/extmods/utils
copying build/lib/hubblestack/extmods/utils/s3.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/utils
copying build/lib/hubblestack/extmods/utils/__init__.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/utils
creating build/bdist.linux-x86_64/egg/hubblestack/extmods/modules
copying build/lib/hubblestack/extmods/modules/nova_loader.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/modules
copying build/lib/hubblestack/extmods/modules/win_pulsar.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/modules
copying build/lib/hubblestack/extmods/modules/pulsar.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/modules
copying build/lib/hubblestack/extmods/modules/conf_publisher.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/modules
copying build/lib/hubblestack/extmods/modules/win_pulsar_winaudit.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/modules
copying build/lib/hubblestack/extmods/modules/__init__.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/modules
copying build/lib/hubblestack/extmods/modules/nebula_osquery.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/modules
copying build/lib/hubblestack/extmods/modules/hubble.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/modules
creating build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
copying build/lib/hubblestack/extmods/grains/osqueryinfo.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
copying build/lib/hubblestack/extmods/grains/systemuuid.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
copying build/lib/hubblestack/extmods/grains/fqdn.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
copying build/lib/hubblestack/extmods/grains/hubbleuuid.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
copying build/lib/hubblestack/extmods/grains/custom_grains_pillar.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
copying build/lib/hubblestack/extmods/grains/splunkconfig.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
copying build/lib/hubblestack/extmods/grains/cloud_details.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
copying build/lib/hubblestack/extmods/grains/configgrains.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
copying build/lib/hubblestack/extmods/grains/__init__.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
copying build/lib/hubblestack/extmods/grains/default_gw.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/grains
creating build/bdist.linux-x86_64/egg/hubblestack/extmods/fileserver
copying build/lib/hubblestack/extmods/fileserver/azurefs.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/fileserver
copying build/lib/hubblestack/extmods/fileserver/s3fs.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/fileserver
copying build/lib/hubblestack/extmods/fileserver/__init__.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/fileserver
copying build/lib/hubblestack/extmods/__init__.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods
creating build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/splunk_pulsar_return.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/logstash_pulsar_return.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/graylog_pulsar_return.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/sqlite.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/graylog_nova_return.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/logstash_nova_return.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/slack_pulsar_returner.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/__init__.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/splunk_nova_return.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/splunk_nebula_return.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/logstash_nebula_return.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/extmods/returners/graylog_nebula_return.py -> build/bdist.linux-x86_64/egg/hubblestack/extmods/returners
copying build/lib/hubblestack/splunklogging.py -> build/bdist.linux-x86_64/egg/hubblestack
copying build/lib/hubblestack/__init__.py -> build/bdist.linux-x86_64/egg/hubblestack
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/hangtime.py to hangtime.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/win_gp.py to win_gp.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/openssl.py to openssl.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/firewall.py to firewall.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/win_pkg.py to win_pkg.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/win_reg.py to win_reg.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/sysctl.py to sysctl.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/netstat.py to netstat.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/cve_scan_v2.py to cve_scan_v2.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/win_auditpol.py to win_auditpol.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/vulners_scanner.py to vulners_scanner.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/misc.py to misc.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/systemctl.py to systemctl.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/cve_scan.py to cve_scan.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/mount.py to mount.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/service.py to service.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/pkg.py to pkg.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/grep.py to grep.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/command.py to command.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/stat_nova.py to stat_nova.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/win_firewall.py to win_firewall.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/win_secedit.py to win_secedit.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/hubblestack_nova/pkgng_audit.py to pkgng_audit.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/files/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/daemon.py to daemon.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/utils/s3.py to s3.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/modules/nova_loader.py to nova_loader.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/modules/win_pulsar.py to win_pulsar.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/modules/pulsar.py to pulsar.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/modules/conf_publisher.py to conf_publisher.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/modules/win_pulsar_winaudit.py to win_pulsar_winaudit.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/modules/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/modules/nebula_osquery.py to nebula_osquery.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/modules/hubble.py to hubble.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/grains/osqueryinfo.py to osqueryinfo.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/grains/systemuuid.py to systemuuid.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/grains/fqdn.py to fqdn.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/grains/hubbleuuid.py to hubbleuuid.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/grains/custom_grains_pillar.py to custom_grains_pillar.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/grains/splunkconfig.py to splunkconfig.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/grains/cloud_details.py to cloud_details.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/grains/configgrains.py to configgrains.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/grains/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/grains/default_gw.py to default_gw.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/fileserver/azurefs.py to azurefs.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/fileserver/s3fs.py to s3fs.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/fileserver/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/splunk_pulsar_return.py to splunk_pulsar_return.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/logstash_pulsar_return.py to logstash_pulsar_return.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/graylog_pulsar_return.py to graylog_pulsar_return.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/sqlite.py to sqlite.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/graylog_nova_return.py to graylog_nova_return.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/logstash_nova_return.py to logstash_nova_return.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/slack_pulsar_returner.py to slack_pulsar_returner.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/splunk_nova_return.py to splunk_nova_return.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/splunk_nebula_return.py to splunk_nebula_return.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/logstash_nebula_return.py to logstash_nebula_return.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/extmods/returners/graylog_nebula_return.py to graylog_nebula_return.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/splunklogging.py to splunklogging.pyc
byte-compiling build/bdist.linux-x86_64/egg/hubblestack/__init__.py to __init__.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying hubblestack.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hubblestack.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hubblestack.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hubblestack.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hubblestack.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hubblestack.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
hubblestack.daemon: module references __file__
hubblestack.extmods.modules.nova_loader: module references __file__
hubblestack.extmods.modules.nova_loader: module MAY be using inspect.trace
creating 'dist/hubblestack-2.4.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing hubblestack-2.4.1-py2.7.egg
removing '/usr/lib/python2.7/site-packages/hubblestack-2.4.1-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/hubblestack-2.4.1-py2.7.egg
Extracting hubblestack-2.4.1-py2.7.egg to /usr/lib/python2.7/site-packages
hubblestack 2.4.1 is already the active version in easy-install.pth
Installing hubble script to /usr/bin

Installed /usr/lib/python2.7/site-packages/hubblestack-2.4.1-py2.7.egg
Processing dependencies for hubblestack==2.4.1
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    'Topic :: System :: Systems Administration',
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 617, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 668, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 716, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 847, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2602, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2597, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2930, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2906, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected ',' or end-of-list in tornado>=4.2.1,<6.0; python_version < '3' at ; python_version < '3'

```

**Comment by claudekenni** [comment]
Hubble itself seems to be installed but it won't run

```
root@.:/root/hubble > /usr/bin/pip list
/usr/lib/python2.7/site-packages/pip-18.0-py2.7.egg/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 3, 1]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Package                      Version
---------------------------- ---------
backports.ssl-match-hostname 3.5.0.1
certifi                      2018.4.16
cffi                         1.5.2
configobj                    4.7.2
croniter                     0.3.25
cryptography                 1.3.1
decorator                    3.4.0
enum34                       1.1.3
futures                      3.2.0
gitdb2                       2.0.4
GitPython                    2.1.11
hubblestack                  2.4.1
idna                         2.0
ipaddress                    1.0.14
Jinja2                       2.6
MarkupSafe                   0.18
msgpack                      0.5.6
msgpack-python               0.4.6
netaddr                      0.7.12
numpy                        1.8.0
pip                          18.0
psutil                       1.2.1
pyasn1                       0.1.9
pyasn1-modules               0.0.5
pycparser                    2.10
pycrypto                     2.6.1
pycurl                       7.19.0
pygobject                    3.20.1
pyinotify                    0.9.6
pyOpenSSL                    16.0.0
PyPAM                        0.5.0
pypyodbc                     1.3.4
python-dateutil              2.7.3
pyudev                       0.16.1
PyYAML                       3.12
pyzmq                        14.0.0
requests                     2.8.1
salt                         2016.11.4
salt-ssh                     2018.3.2
setuptools                   40.0.0
simplejson                   3.3.1
six                          1.9.0
smmap2                       2.0.4
SSSDConfig                   1.13.4
suds                         0.4
tornado                      4.2.1
```

```
root@.:/root/hubble > hubble
Traceback (most recent call last):
  File "/usr/bin/hubble", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 847, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2602, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2597, in _dep_map
    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2930, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2906, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected ',' or end-of-list in tornado>=4.2.1,<6.0; python_version < '3' at ; python_version < '3'
```

**Comment by basepi** [comment]
I've seen this issue before -- you need to update your setuptools via pip.

```
pip install --upgrade setuptools
```

Then tell it to install again. It's specifically the salt-ssh install that failed.
