### ISSUE TITLE
Hubble not working on windows due to pid file

### ISSUE THREAD

**Issue by yassingh** [hubblestack/hubble#476]
It seems that the lastest build of hubble is not working on windows. Hubble daemon tries to write pid to 'C:\Program Files (x86)\hubble \var\run\hubble.pid' after some time. Since this file does not exist on windows, hubble daemon stops working.

Have a look at the logs for better understanding:
```
2018-10-23 13:25:20 [salt.log.setup ][ERROR   ] An un-handled exception was caught by salt's global exception handler:
IOError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\hubble\\var\\run\\hubble.pid'
Traceback (most recent call last):
  File "hubble.py", line 5, in <module>
  File "hubblestack\daemon.py", line 68, in run
    main()
  File "hubblestack\daemon.py", line 156, in main
    create_pidfile()
  File "hubblestack\daemon.py", line 778, in create_pidfile
    with open(__opts__['pidfile'], 'w') as f:
IOError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\hubble\\var\\run\\hubble.pid'
```

@basepi

**Comment by basepi** [comment]
https://jira.corp.adobe.com/browse/CSTREQ-45468
