### ISSUE TITLE
Documentation on vulners cve (since old cve profile has been deprecated)

### ISSUE THREAD

**Issue by AfterSpencer** [hubblestack/hubble#490]
I am having trouble getting CVE scan data since the cve scan has been moved to vulners.py

Is there documentation on this? If so, I will look it over to see if I can figure out what is wrong.

If not here is the relevant data:

```
[root@hostname cve]# pwd
/srv/salt/hubblestack_data/hubblestack_nova_profiles/cve
[root@hostname cve]# cat vulners.yaml
vulners_scanner: True
vulners_api_key: <my key>
```

```
pwd; cat top.nova
/srv/salt/hubblestack_data/hubblestack_nova_profiles
# Default top.nova
#
# Subscribes to CIS, cve_scan, and misc.yaml for miscellaneous checks

nova:
  '*':
    #- security.meltdown_spectre
    - security.ssh_passwordauthentication
    #- cis.distribution-independent-linux-level-1-all-v1-1-0
    - vulners
```

Output from hubble audit:

```
hubble hubble.audit
{'Compliance': '0%',
 'Failure': [{'sshd-authenticationmethods-publickey': 'Check for explicitly configured publickey authentication method'},
             {'sshd-passwordauthentication-no': 'Ensure password authentication is disabled in sshd_config'}]}
```

Also, I would like to make sure the functionality in the previous scan to be able to use a local json file for CVE data was still supported.

**Comment by basepi** [comment]
I don't think that functionality is still supported, unfortunately. I think vulners wanted to move away from that type of usage because it was really hammering their servers to download all of that data. We may have to find another data source if that's something we still want to support.

I think your problem above is the vulners line in your top.nova:

```
nova:
  '*':
    #- security.meltdown_spectre
    - security.ssh_passwordauthentication
    #- cis.distribution-independent-linux-level-1-all-v1-1-0
    - cve.vulners
```

Try that ^

**Comment by AfterSpencer** [comment]
My organization has another vulnerability source we would like to build a suitable file from. I was also thinking about creating a job that downloads the correct file once a day from vulners and then hosting it locally for my boxes to pull from so as not to overload vulners.

I will give the changes you suggested a try and let you know.

**Comment by AfterSpencer** [comment]
Looks like the output is the same with cve.vulners in top.nova

```
cat top.nova
# Default top.nova
#
# Subscribes to CIS, cve_scan, and misc.yaml for miscellaneous checks

nova:
  '*':
    #- security.meltdown_spectre
    - security.ssh_passwordauthentication
    #- cis.distribution-independent-linux-level-1-all-v1-1-0
    - cve.vulners
```
```
[root@hostname hubblestack_nova_profiles]# hubble hubble.audit
{'Compliance': '0%',
 'Failure': [{'sshd-authenticationmethods-publickey': 'Check for explicitly configured publickey authentication method'},
             {'sshd-passwordauthentication-no': 'Ensure password authentication is disabled in sshd_config'}]}
```

**Comment by basepi** [comment]
Odd. Could you run the job with `-vvv` so I can see the debug output? It will be long, so you can stick it in a gist or a pastebin.

**Comment by AfterSpencer** [comment]
```
hubble hubble.audit -vvv
[DEBUG   ] watching for process hangs HT(600.00s, tag=hubble:rg)
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/hubble/hubble
[DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80
[DEBUG   ] Starting new HTTP connection (1): 169.254.169.254:80
[DEBUG   ] Fetching custom grains and pillar details
[DEBUG   ] Done with fetching custom grains and pillar details
[INFO    ] Executing command 'ip route show to 0/0' in directory '/root'
[DEBUG   ] stdout: default via <gateway> dev eth0
[DEBUG   ] HT(600.00s, tag=hubble:rg) exited with-block normally
[DEBUG   ] timer stack empty after HT(600.00s, tag=hubble:rg), resetting signals/itimers
[DEBUG   ] nolonger watching for process hangs HT(600.00s, tag=hubble:rg)
[DEBUG   ] LazyLoaded config.get
[INFO    ] Setting up the fileclient/fileserver
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Parsed args: [] | Parsed kwargs: {}
[INFO    ] Executing user-requested function hubble.audit
[DEBUG   ] LazyLoaded hubble.audit
[DEBUG   ] syncing nova modules
[DEBUG   ] LazyLoaded cp.cache_dir
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[INFO    ] Caching directory 'hubblestack_nova_profiles/' for environment 'base'
[DEBUG   ] In saltenv 'base', looking at rel_path 'hubblestack_nova_profiles/centos_7.json' to resolve 'salt://hubblestack_nova_profiles/centos_7.json'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/hubble/files/base/hubblestack_nova_profiles/centos_7.json' to resolve 'salt://hubblestack_nova_profiles/centos_7.json'
[DEBUG   ] In saltenv 'base', looking at rel_path 'hubblestack_nova_profiles/cve/vulners.yaml' to resolve 'salt://hubblestack_nova_profiles/cve/vulners.yaml'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/hubble/files/base/hubblestack_nova_profiles/cve/vulners.yaml' to resolve 'salt://hubblestack_nova_profiles/cve/vulners.yaml'
[DEBUG   ] In saltenv 'base', looking at rel_path 'hubblestack_nova_profiles/cve_scan.yaml' to resolve 'salt://hubblestack_nova_profiles/cve_scan.yaml'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/hubble/files/base/hubblestack_nova_profiles/cve_scan.yaml' to resolve 'salt://hubblestack_nova_profiles/cve_scan.yaml'
[DEBUG   ] In saltenv 'base', looking at rel_path 'hubblestack_nova_profiles/top.nova' to resolve 'salt://hubblestack_nova_profiles/top.nova'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/hubble/files/base/hubblestack_nova_profiles/top.nova' to resolve 'salt://hubblestack_nova_profiles/top.nova'
[DEBUG   ] In saltenv 'base', looking at rel_path 'hubblestack_nova_profiles/vulners.yaml' to resolve 'salt://hubblestack_nova_profiles/vulners.yaml'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/hubble/files/base/hubblestack_nova_profiles/vulners.yaml' to resolve 'salt://hubblestack_nova_profiles/vulners.yaml'
[DEBUG   ] loading nova modules
[DEBUG   ] Error loading nova./win_secedit.py: This audit module only runs on windows
[DEBUG   ] Error loading nova./win_firewall.py: This audit module only runs on windows
[DEBUG   ] Error loading nova./pkgng_audit.py: This audit module only runs on FreeBSD
[DEBUG   ] Error loading nova./win_gp.py: This audit module only runs on windows
[DEBUG   ] LazyLoaded network.netstat
[DEBUG   ] Error loading nova./win_reg.py: This audit module only runs on windows
[DEBUG   ] Failed to import nova /vulners_scanner.py:
Traceback (most recent call last):
  File "/opt/hubble/hubble-libs/hubblestack/extmods/modules/nova_loader.py", line 1931, in _load_module
    ), fn_, fpath, desc)
  File "/opt/hubble/hubble-libs/hubblestack/files/hubblestack_nova/vulners_scanner.py", line 25, in <module>
    import vulners
ImportError: No module named vulners
[DEBUG   ] Error loading nova./win_pkg.py: This audit module only runs on windows
[DEBUG   ] Error loading nova./win_auditpol.py: This audit module only runs on windows
[DEBUG   ] LazyLoaded match.compound
[DEBUG   ] compound_match: hostname ? *
[DEBUG   ] compound_match hostname ? "*" => "True"
[DEBUG   ] nova_kwargs: {}
[DEBUG   ] service audit __data__:
[DEBUG   ] {'openssl': []}
[DEBUG   ] service audit __tags__:
[DEBUG   ] {}
[DEBUG   ] LazyLoaded cmd.run_all
[INFO    ] Executing command 'grep   ^\\s*AuthenticationMethods\\s.*publickey.* /etc/ssh/sshd_config' in directory '/root'
[DEBUG   ] retcode: 1
[INFO    ] Executing command 'grep   ^\\s*PasswordAuthentication /etc/ssh/sshd_config' in directory '/root'
[DEBUG   ] retcode: 1
{'Compliance': '0%',
 'Failure': [{'sshd-authenticationmethods-publickey': 'Check for explicitly configured publickey authentication method'},
             {'sshd-passwordauthentication-no': 'Ensure password authentication is disabled in sshd_config'}]}
```

**Comment by AfterSpencer** [comment]
```
[DEBUG   ] Failed to import nova /vulners_scanner.py:
Traceback (most recent call last):
  File "/opt/hubble/hubble-libs/hubblestack/extmods/modules/nova_loader.py", line 1931, in _load_module
    ), fn_, fpath, desc)
  File "/opt/hubble/hubble-libs/hubblestack/files/hubblestack_nova/vulners_scanner.py", line 25, in <module>
    import vulners
ImportError: No module named vulners
```

**Comment by basepi** [comment]
Interesting. What version of hubble are you using? I'm fairly certain that should be packaged in with 2.4.7 but I'm not sure about previous versions.

**Comment by AfterSpencer** [comment]
```
hubble --version
2.4.7
```

**Comment by basepi** [comment]
Huh. Installed with our packages from our release page or from source?

**Comment by AfterSpencer** [comment]
From the release page, I didn't build it from source.

**Comment by AfterSpencer** [comment]
No worries, I appreciate your repsonses too. We are in the beginning testing phase on the project we want to use it for.

**Comment by dgmorrisjr** [comment]
We have also been using hubble for disconnected servers and need to be able to download the datasource for offline scanning.

**Comment by basepi** [comment]
Ref #499

**Comment by AfterSpencer** [comment]
Thanks! I will give it a try with the next release.

Does this allow for offline CVE scanning too?

**Comment by basepi** [comment]
Unfortunately no. #499 tracks that.

**Comment by AfterSpencer** [comment]
```
[DEBUG   ] Failed to import nova /vulners_scanner.py:
Traceback (most recent call last):
  File "/opt/hubble/hubble-libs/hubblestack/extmods/modules/nova_loader.py", line 1931, in _load_module
    ), fn_, fpath, desc)
  File "/opt/hubble/hubble-libs/hubblestack/files/hubblestack_nova/vulners_scanner.py", line 25, in <module>
    import vulners
ImportError: No module named vulners
```

Did this bug ever get fixed?

**Comment by basepi** [comment]
I'm pretty sure it's fixed but didn't do a 2.4.8 -- it will be in the upcoming 3.0.0 release.

**Comment by AfterSpencer** [comment]
Okay, what is the ETA on 3.0.0?

**Comment by basepi** [comment]
It's feature-frozen here: https://github.com/hubblestack/hubble/tree/3.0

We're currently testing and prepping, shooting for an official release by end of April, assuming no big issues.
