### ISSUE TITLE
Running hubble hubble.audit on Server 2012R2 results in FileserverConfigError errors

### ISSUE THREAD

**Issue by alias454** [hubblestack/hubble#492]
After installing the latest version of hubble on a fresh install of a fully patched Windows Server 2012R2 instance I see errors when trying to launch the NOVA audit

```
    [ERROR   ] The git command line utility is required when using the 'pygit2' gitfs_provider.
    [ERROR   ] The git command line utility is required when using the 'gitpython' gitfs_provider.
    [CRITICAL] No suitable gitfs provider module is installed.
    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    FileserverConfigError: Failed to load gitfs
    Traceback (most recent call last):
      File "hubble.py", line 5, in <module>
      File "hubblestack\daemon.py", line 68, in run
      File "hubblestack\daemon.py", line 87, in main
      File "site-packages\salt\utils\gitfs.py", line 2667, in __new__
      File "site-packages\salt\utils\gitfs.py", line 2084, in __init__
      File "site-packages\salt\utils\gitfs.py", line 2467, in verify_provider
      File "site-packages\salt\utils\gitfs.py", line 211, in failhard
    FileserverConfigError: Failed to load gitfs
    Traceback (most recent call last):
      File "hubble.py", line 5, in <module>
      File "hubblestack\daemon.py", line 68, in run
      File "hubblestack\daemon.py", line 87, in main
      File "site-packages\salt\utils\gitfs.py", line 2667, in __new__
      File "site-packages\salt\utils\gitfs.py", line 2084, in __init__
      File "site-packages\salt\utils\gitfs.py", line 2467, in verify_provider
      File "site-packages\salt\utils\gitfs.py", line 211, in failhard
    salt.exceptions.FileserverConfigError: Failed to load gitfs
    Failed to execute script hubble
```

This is using the Windows installer Hubble-v2.4.7-Setup.exe

**Comment by basepi** [comment]
The problem is that git is not on your path. When you run the audit through the scheduled job, I'm pretty sure the daemon handles that automatically. But for one-off jobs in powershell or cmd.exe, you need to make sure the portable git exe is on your path.

Or, you can just run your commands from within `C:\Program Files (x86)\Hubble\PortableGit\git-cmd.exe`. We'll get this added to the docs.

Keep me posted if that doesn't solve your issue.

**Comment by alias454** [comment]
Thanks, I was able to get it working by launching the git shell first and by setting the path using
`set path="C:\Program Files (x86)\Hubble\PortableGit\cmd";%path%`

**Comment by basepi** [comment]
Perfect. Thanks for following up!
