### ISSUE TITLE
Errors after install on server 2016

### ISSUE THREAD

**Issue by brettnelsen** [hubblestack/hubble#552]
2019-02-23 13:58:59 [salt.utils.gitfs][ERROR   ] Error occurred fetching gitfs remote 'https://github.com/hubblestack/hubblestack_data.git': user cancelled certificate check
Traceback (most recent call last):
  File "site-packages\salt\utils\gitfs.py", line 1703, in _fetch
  File "site-packages\pygit2\remote.py", line 405, in fetch
  File "site-packages\pygit2\errors.py", line 64, in check_error
GitError: user cancelled certificate check

I have git installed and i also pulled the files for the "hubblestack_data" and placed them in C:\Program Files (x86)\Hubble\hubblestack\files.  Not sure if that is the right place but before and after adding those files I get the same errors.

**Comment by basepi** [comment]
So with the default config, hubble tries to fetch its profiles from `
https://github.com/hubblestack/hubblestack_data.git`.

To remove the error you can remove [this line](https://github.com/hubblestack/hubble/blob/8412e0db4aa413c2c39b3235810c788dee0fd105/conf/hubble#L23) from `C:\Program Files (x86)\Hubble\etc\hubble\hubble`. Then you'll need to tell hubble where to find the local files, by adding the following lines:

```
file_roots:
  base:
    - 'C:\Program Files (x86)\Hubble\hubblestack\files'
```

That should get it working for you. Keep me posted if you have any other issues.
