### ISSUE TITLE
How to run this on Windows server,i have installed the hubble in windows server but not sure how to run hubble.audit

### ISSUE THREAD

**Issue by dKumar-pki** [hubblestack/hubble#669]

**Comment by dKumar-pki** [comment]
PS C:\Program Files (x86)\Hubble> hubble hubble.ping
16:21:16 [ERROR] The git command line utility is required when using the 'pygit2' gitfs_provider.
16:21:16 [ERROR] The git command line utility is required when using the 'gitpython' gitfs_provider.
16:21:16 [CRITICAL] No suitable gitfs provider module is installed.
16:21:16 [ERROR] An un-handled exception was caught by salt's global exception handler:
FileserverConfigError: Failed to load gitfs
Traceback (most recent call last):
  File "hubble.py", line 5, in <module>
  File "hubblestack\daemon.py", line 68, in run
    main()
  File "hubblestack\daemon.py", line 87, in main
    per_remote_only=salt.fileserver.gitfs.PER_REMOTE_ONLY
  File "site-packages\salt\utils\gitfs.py", line 2667, in __new__
  File "site-packages\salt\utils\gitfs.py", line 2084, in __init__
  File "site-packages\salt\utils\gitfs.py", line 2467, in verify_provider
  File "site-packages\salt\utils\gitfs.py", line 211, in failhard
FileserverConfigError: Failed to load gitfs
Traceback (most recent call last):
  File "hubble.py", line 5, in <module>
  File "hubblestack\daemon.py", line 68, in run
    main()
  File "hubblestack\daemon.py", line 87, in main
    per_remote_only=salt.fileserver.gitfs.PER_REMOTE_ONLY
  File "site-packages\salt\utils\gitfs.py", line 2667, in __new__
  File "site-packages\salt\utils\gitfs.py", line 2084, in __init__
  File "site-packages\salt\utils\gitfs.py", line 2467, in verify_provider
  File "site-packages\salt\utils\gitfs.py", line 211, in failhard
salt.exceptions.FileserverConfigError: Failed to load gitfs
Failed to execute script hubble

**Comment by basepi** [comment]
Sorry about this! It's a problem in our documentation for windows. Basically to run hubble using gitfs, you have to run commands from the git command line (`C:\Program Files (x86)\Hubble\PortableGit\git-cmd.exe`)

This step is handled for you if you use the system service.

I should also point out that you want `test.ping`, not `hubble.ping`.

**Comment by dKumar-pki** [comment]
Thanks for your reply. But i am getting another error while running audit command for my windows machine.
C:\Program Files (x86)\Hubble\PortableGit>hubble test.ping
True

C:\Program Files (x86)\Hubble\PortableGit>hubble hubble.audit
15:44:26 [ERROR] An un-handled exception was caught by salt's global exception h
andler:
AttributeError: '_pygit2.Reference' object has no attribute 'get_object'
Traceback (most recent call last):
  File "hubble.py", line 5, in <module>
  File "hubblestack\daemon.py", line 68, in run
  File "hubblestack\daemon.py", line 131, in main
  File "hubblestack\daemon.py", line 418, in run_function
  File "hubblestack\status.py", line 387, in inner
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 118, in
audit
    labels=labels)
  File "hubblestack\status.py", line 387, in inner
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 438, in
top
    load()
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 593, in
load
    sync()
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 569, in
sync
    cached = __salt__['cp.cache_dir'](path, saltenv=saltenv)
  File "C:\PROGRA~2\Hubble\salt\modules\cp.py", line 586, in cache_dir
    path, saltenv, include_empty, include_pat, exclude_pat
  File "site-packages\salt\fileclient.py", line 239, in cache_dir
  File "site-packages\salt\fileclient.py", line 1272, in file_list
  File "site-packages\salt\fileserver\__init__.py", line 874, in send
  File "site-packages\salt\utils\decorators\__init__.py", line 656, in wrapped
  File "site-packages\salt\fileserver\__init__.py", line 755, in file_list
  File "C:\PROGRA~2\Hubble\salt\fileserver\gitfs.py", line 185, in file_list
    return _gitfs().file_list(load)
  File "site-packages\salt\utils\gitfs.py", line 2934, in file_list
  File "site-packages\salt\utils\gitfs.py", line 2911, in _file_lists
  File "site-packages\salt\utils\gitfs.py", line 1777, in file_list
  File "site-packages\salt\utils\gitfs.py", line 1016, in get_tree
  File "site-packages\salt\utils\gitfs.py", line 1852, in get_tree_from_branch
AttributeError: '_pygit2.Reference' object has no attribute 'get_object'
Traceback (most recent call last):
  File "hubble.py", line 5, in <module>
  File "hubblestack\daemon.py", line 68, in run
  File "hubblestack\daemon.py", line 131, in main
  File "hubblestack\daemon.py", line 418, in run_function
  File "hubblestack\status.py", line 387, in inner
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 118, in
audit
    labels=labels)
  File "hubblestack\status.py", line 387, in inner
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 438, in
top
    load()
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 593, in
load
    sync()
  File "C:\PROGRA~2\Hubble\hubblestack\extmods\modules\hubble.py", line 569, in
sync
    cached = __salt__['cp.cache_dir'](path, saltenv=saltenv)
  File "C:\PROGRA~2\Hubble\salt\modules\cp.py", line 586, in cache_dir
    path, saltenv, include_empty, include_pat, exclude_pat
  File "site-packages\salt\fileclient.py", line 239, in cache_dir
  File "site-packages\salt\fileclient.py", line 1272, in file_list
  File "site-packages\salt\fileserver\__init__.py", line 874, in send
  File "site-packages\salt\utils\decorators\__init__.py", line 656, in wrapped
  File "site-packages\salt\fileserver\__init__.py", line 755, in file_list
  File "C:\PROGRA~2\Hubble\salt\fileserver\gitfs.py", line 185, in file_list
    return _gitfs().file_list(load)
  File "site-packages\salt\utils\gitfs.py", line 2934, in file_list
  File "site-packages\salt\utils\gitfs.py", line 2911, in _file_lists
  File "site-packages\salt\utils\gitfs.py", line 1777, in file_list
  File "site-packages\salt\utils\gitfs.py", line 1016, in get_tree
  File "site-packages\salt\utils\gitfs.py", line 1852, in get_tree_from_branch
AttributeError: '_pygit2.Reference' object has no attribute 'get_object'
Failed to execute script hubble

**Comment by basepi** [comment]
Hmmm, that is odd. Can you show me your hubble config?

**Comment by dKumar-pki** [comment]
I have not configure anything just installed it and try to run. It will be better if you can provide me any documentation for windows.

**Comment by dKumar-pki** [comment]
Hi, Please provide me the process to work with hubble on Windows platform?

**Comment by basepi** [comment]
Sorry for the delays here, I've been traveling and on PTO and am finally catching up.

The config is in `C:\Program Files (x86)\Hubble\etc\hubble\hubble`

**Comment by praksinha** [comment]
@dKumar-pki You can refer https://github.com/hubblestack/hubble/blob/develop/pkg/windows/hubble.conf config to start with. If you use Splunk, you must specify correct values for token, index, indexer etc. If you use any other log aggregator like logstash, you should update the config accordingly (returner block towards the end of config).

Although it is recommended to run Hubble as a service on Windows and when you install Hubble, Hubble is configured as service already. But if you want to just test it out you can run following command:
