### ISSUE TITLE
Splunk Nebula returner doesn't work when nebula is run with verbose=True

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble#70]
_From @basepi on March 7, 2017 22:35_

_From @mew1033 on August 22, 2016 23:22_

```
2016-08-22 16:20:31,430 [salt.minion                                          ][ERROR   ][496] The return failed for job 20160822162030254018 string indices must be integers, not str
2016-08-22 16:20:31,431 [salt.minion                                          ][ERROR   ][496] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 1418, in _thread_return
    )](ret)
  File "/var/cache/salt/minion/extmods/returners/splunk_nebula_return.py", line 59, in returner
    for query_result in query_results['data']:
TypeError: string indices must be integers, not str
```

_Copied from original issue: hubblestack/quasar#20_

_Copied from original issue: hubblestack/hubble-salt#22_

**Comment by basepi** [comment]
This should be pretty trivial to fix, by the way. If it's run in verbose mode, then instead of being a list of strings, it's a list of dicts. Inside of each dict will be a `'query_result'` key, which is the non-verbose result of the query.

**Comment by basepi** [comment]
I doubt this is still true but if it is we'll fix is later.
