### ISSUE TITLE
[CoreOS][pkg module] PKG module is not able to LazyLoad pkg.version on CoreOS

### ISSUE THREAD

**Issue by vishsriv** [hubblestack/hubble#94]
Error is coming while running pkg audits on CoreOS.
E.g,
Following audit is giving error:
```
pkg:
  whitelist:
    tcp_wrappers:
      data:
        '*CoreOS*':
        - tcp_wrappers: CIS-3.4.1
      description: Ensure TCP Wrappers is installed
```
Error:
```
[DEBUG   ] Could not LazyLoad pkg.version: 'pkg.version' is not available.
[ERROR   ] Exception occurred in nova module:
[ERROR   ] Traceback (most recent call last):
  File "/opt/hubble/hubble-libs/hubblestack/extmods/modules/hubble.py", line 264, in _run_audit
    ret = func(data_list, tags, debug=debug)
  File "/var/cache/hubble/files/base/hubblestack_nova/pkg.py", line 152, in audit
    if __salt__['pkg.version'](name):
  File "salt/loader.py", line 1087, in __getitem__
  File "salt/utils/lazy.py", line 101, in __getitem__
KeyError: 'pkg.version'
```

**Comment by basepi** [comment]
This is an expected error. Because CoreOS doesn't have a package manager, salt's underlying pkg libraries don't load.

We haven't figured out a good workaround, but honestly for DMa at Adobe we're probably just going to pull CoreOS versions from splunk and compare against CVEs reported by the CoreOS team in their releases.
